binding_modes:
- keybindings:
  - bindings:
    - h
    - left
    commands:
    - resize --width -2%
  - bindings:
    - l
    - right
    commands:
    - resize --width +2%
  - bindings:
    - k
    - up
    commands:
    - resize --height +2%
  - bindings:
    - j
    - down
    commands:
    - resize --height -2%
  - bindings:
    - escape
    - enter
    commands:
    - wm-disable-binding-mode --name resize
  name: resize
gaps:
  inner_gap: 20px
  outer_gap:
    bottom: -30px
    left: 20px
    right: 20px
    top: -30px
  scale_with_dpi: true
general:
  config_reload_commands: []
  cursor_jump:
    enabled: true
    trigger: monitor_focus
  focus_follows_cursor: true
  hide_method: cloak
  show_all_in_taskbar: false
  shutdown_commands:
  - shell-exec taskkill /IM yasb.exe /F
  - shell-exec taskkill /IM zebar.exe /F
  - shell-exec powershell -Command "Get-CimInstance Win32_Process | Where-Object {
    $_.CommandLine -like '*yasb_glazewm_auto_hide.py*' } | Stop-Process -Force"
  startup_commands:
  - shell-exec yasb
  - shell-exec C:/Users/mert/.config/yasb/start_yasb_glazewm_hidden.bat
  toggle_workspace_on_refocus: false
keybindings:
- bindings:
  - alt+h
  - alt+left
  commands:
  - focus --direction left
- bindings:
  - alt+l
  - alt+right
  commands:
  - focus --direction right
- bindings:
  - alt+k
  - alt+up
  commands:
  - focus --direction up
- bindings:
  - alt+j
  - alt+down
  commands:
  - focus --direction down
- bindings:
  - alt+shift+h
  - alt+shift+left
  commands:
  - move --direction left
- bindings:
  - alt+shift+l
  - alt+shift+right
  commands:
  - move --direction right
- bindings:
  - alt+shift+k
  - alt+shift+up
  commands:
  - move --direction up
- bindings:
  - alt+shift+j
  - alt+shift+down
  commands:
  - move --direction down
- bindings:
  - alt+u
  commands:
  - resize --width -2%
- bindings:
  - alt+p
  commands:
  - resize --width +2%
- bindings:
  - alt+o
  commands:
  - resize --height +2%
- bindings:
  - alt+i
  commands:
  - resize --height -2%
- bindings:
  - alt+r
  commands:
  - wm-enable-binding-mode --name resize
- bindings:
  - alt+shift+p
  commands:
  - wm-toggle-pause
- bindings:
  - alt+v
  commands:
  - toggle-tiling-direction
- bindings:
  - alt+space
  commands:
  - wm-cycle-focus
- bindings:
  - alt+shift+space
  commands:
  - toggle-floating --centered
- bindings:
  - alt+t
  commands:
  - toggle-tiling
- bindings:
  - alt+f
  commands:
  - toggle-fullscreen
- bindings:
  - alt+q
  commands:
  - toggle-minimized
- bindings:
  - alt+shift+q
  commands:
  - close
- bindings:
  - alt+shift+e
  commands:
  - wm-exit
- bindings:
  - alt+shift+r
  commands:
  - wm-reload-config
- bindings:
  - alt+shift+w
  commands:
  - wm-redraw
- bindings:
  - alt+enter
  commands:
  - shell-exec cmd
- bindings:
  - alt+s
  commands:
  - focus --next-active-workspace
- bindings:
  - alt+a
  commands:
  - focus --prev-active-workspace
- bindings:
  - alt+d
  commands:
  - focus --recent-workspace
- bindings:
  - alt+1
  commands:
  - focus --workspace 1
- bindings:
  - alt+2
  commands:
  - focus --workspace 2
- bindings:
  - alt+3
  commands:
  - focus --workspace 3
- bindings:
  - alt+4
  commands:
  - focus --workspace 4
- bindings:
  - alt+5
  commands:
  - focus --workspace 5
- bindings:
  - alt+6
  commands:
  - focus --workspace 6
- bindings:
  - alt+7
  commands:
  - focus --workspace 7
- bindings:
  - alt+8
  commands:
  - focus --workspace 8
- bindings:
  - alt+9
  commands:
  - focus --workspace 9
- bindings:
  - alt+shift+a
  commands:
  - move-workspace --direction left
- bindings:
  - alt+shift+f
  commands:
  - move-workspace --direction right
- bindings:
  - alt+shift+d
  commands:
  - move-workspace --direction up
- bindings:
  - alt+shift+s
  commands:
  - move-workspace --direction down
- bindings:
  - alt+shift+1
  commands:
  - move --workspace 1
  - focus --workspace 1
- bindings:
  - alt+shift+2
  commands:
  - move --workspace 2
  - focus --workspace 2
- bindings:
  - alt+shift+3
  commands:
  - move --workspace 3
  - focus --workspace 3
- bindings:
  - alt+shift+4
  commands:
  - move --workspace 4
  - focus --workspace 4
- bindings:
  - alt+shift+5
  commands:
  - move --workspace 5
  - focus --workspace 5
- bindings:
  - alt+shift+6
  commands:
  - move --workspace 6
  - focus --workspace 6
- bindings:
  - alt+shift+7
  commands:
  - move --workspace 7
  - focus --workspace 7
- bindings:
  - alt+shift+8
  commands:
  - move --workspace 8
  - focus --workspace 8
- bindings:
  - alt+shift+9
  commands:
  - move --workspace 9
  - focus --workspace 9
window_behavior:
  initial_state: tiling
  state_defaults:
    floating:
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: false
      shown_on_top: false
window_effects:
  focused_window:
    border:
      color: '#8dbcff'
      enabled: true
    corner_style:
      enabled: false
      style: square
    hide_title_bar:
      enabled: false
    transparency:
      enabled: false
      opacity: 95%
  other_windows:
    border:
      color: '#a1a1a1'
      enabled: true
    corner_style:
      enabled: false
      style: square
    hide_title_bar:
      enabled: false
    transparency:
      enabled: false
      opacity: 0%
window_rules:
- commands:
  - move --workspace 1
  match:
  - window_process:
      equals: zen
- commands:
  - move --workspace 2
  match:
  - window_process:
      equals: Discord
- commands:
  - move --workspace 3
  match:
  - window_process:
      equals: Code - Insiders
- commands:
  - move --workspace 4
  match:
  - window_process:
      equals: Spotify
- commands:
  - ignore
  match:
  - window_process:
      equals: zebar
  - window_process:
      equals: yasb
  - window_class:
      regex: Chrome_WidgetWin_1|MozillaDialogClass
    window_title:
      regex: '[Pp]icture.in.[Pp]icture'
  - window_class:
      regex: HwndWrapper\[PowerToys\.PowerAccent.*?\]
    window_process:
      equals: PowerToys
  - window_process:
      equals: PowerToys
    window_title:
      regex: .*? - Peek
  - window_class:
      regex: HwndWrapper
    window_process:
      equals: Lively
  - window_class:
      not_regex: XLMAIN
    window_process:
      equals: EXCEL
  - window_class:
      not_regex: OpusApp
    window_process:
      equals: WINWORD
  - window_class:
      not_regex: PPTFrameClass
    window_process:
      equals: POWERPNT
workspaces:
- name: '1'
- name: '2'
- name: '3'
- name: '4'
- name: '5'
- name: '6'
- name: '7'
- name: '8'
- name: '9'
